// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "title": "Hello world!",
    "about": "Go to the about page"
  },
  "Metadata": {
    "title": "PocketMoney",
    "description": "Home finances app for you"
  },
  "FormFields": {
    "email": "Email",
    "password": "Password",
    "signIn": "Sign In",
    "signUp": "Sign Up",
    "singInDesc": "Enter your credentials"
  }
};
export default messages;