// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "title": "Hola Mundo!",
    "about": "Acerca de nosotros",
    "login": "Acceder",
    "signin": "Registrarse"
  },
  "Metadata": {
    "title": "PocketMoney",
    "description": "App de gestión de economía para tu hogar"
  }
};
export default messages;